# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do |lane, options|
    setup_ci
  end

  desc "Run tests"
  lane :tests do
    run_tests(scheme: "RelevantInformer")
  end

  desc "Build project"
  lane :build do
    analyze_commits(match: "*")
    next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]

    markdownChangelog = conventional_changelog(title: "Relevant Informer", format: "markdown")

    add_git_tag(tag: next_version, message: markdownChangelog)
    push_to_git_remote
  end
end
